spring:
  datasource:
    dynamic:
      primary: mybatis #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        gmall:
          url: jdbc:mysql://hadoop102:3306/gmall?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "000000"
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5  #池子中初始有5个连接
            max-active: 20   #最多创建20个
            max-wait: 60000  #连接耗尽时，线程的最大等待时间
            min-idle: 5      #池子中连接的最小存活数
            test-on-borrow: true #线程在借走连接之前，先测试下
            test-on-return: false #线程在归还连接之前，先测试下
            test-while-idle: true #在连接空闲时，不断检测是否是好使的
        mybatis:
          url: jdbc:mysql://hadoop102:3306/Mybatis?useSSL=false&useUnicode=true&characterEncoding=UTF-8
          username: root
          password: "000000"
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            initial-size: 5
            max-active: 20
            max-wait: 60000
            min-idle: 5
            test-on-borrow: true
            test-on-return: false
            test-while-idle: true
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure

mybatis:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true